version: "3.7"
services:
  redis:
    image: redis:latest
    ports:
      - "6739:6739"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=LINKS_BACKEND
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql@102030
      - MYSQL_ROOT_PASSWORD=mysql@102030
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s

volumes:
  mysql:
